In [15]:
import numpy as np

n1 = np.array([10,20,30])
type(n1)

n2 = np.array([[1,2,3,4],[5,6,7,8]])
n2

zeroes_arr = np.zeros((5,5))
zeroes_arr

tens_arr = np.full((5,5),10)
tens_arr

range_arr = np.arange(10,50)
range_arr

range_arr_skip = np.arange(10,100,5)
range_arr_skip

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [21]:
random_arr = np.random.randint(1,100,10)
random_arr

array([73, 22, 94, 25, 66, 11, 95, 90, 94, 69])

In [28]:
shape_arr = np.array([[1,2,3],[4,5,6]])
shape_arr
shape_arr.shape = (3,2)
shape_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
#vertical stack()
first_arr = np.array([1,2,3])
second_arr = np.array([4,5,6])
np.vstack((first_arr,second_arr))




array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
#horizontal stack()
np.hstack((first_arr,second_arr))

array([1, 2, 3, 4, 5, 6])

In [38]:
#column stack()
np.column_stack((second_arr,first_arr))

array([[4, 1],
       [5, 2],
       [6, 3]])

In [42]:
#intersect
arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([5,6,7,8,9,10,1,2])
np.intersect1d(arr1,arr2)

array([1, 2, 5, 6, 7, 8])

In [50]:
#setdiff
np.setdiff1d(arr1,arr2)
np.setdiff1d(arr2,arr1)


array([ 9, 10])

In [56]:
#addition of arrays
arr1 = np.array([20,30,40])
arr2 = np.array([50,60,70])
np.sum([arr1,arr2])

np.sum([arr1,arr2],axis = 0)#y-axis sum
np.sum([arr1,arr2],axis = 1)



array([ 90, 180])

In [63]:
#addition
arr1 = np.array([1,2,3])
arr1 = arr1 + 10
arr1

#multiplication
arr1 = arr1 * 10
arr1

#division
arr1 = arr1 / 10
arr1

array([11., 12., 13.])

In [72]:
# mean
arr1 = np.array([2,3,4,5,1])
np.mean(arr1)

# median
np.median(arr1)

# standard deviation
np.std(arr1)

1.4142135623730951

In [82]:
# matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

matrix[0:3]

#getting particular row and column
matrix[1,:]

array([4, 5, 6])

In [84]:
# transpose
np.transpose(matrix)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [85]:
# matrix multiplication
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
matrix.dot(matrix2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [86]:
# saving numpy array
n1 = np.array([10,1,3])
np.save("numpy_arr_n1",n1)

In [88]:
# loading arr
n2 = np.load("numpy_arr_n1.npy")
n2

array([10,  1,  3])