In [15]:
import numpy as np

n1 = np.array([10,20,30])
type(n1)

n2 = np.array([[1,2,3,4],[5,6,7,8]])
n2

zeroes_arr = np.zeros((5,5))
zeroes_arr

tens_arr = np.full((5,5),10)
tens_arr

range_arr = np.arange(10,50)
range_arr

range_arr_skip = np.arange(10,100,5)
range_arr_skip

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [21]:
random_arr = np.random.randint(1,100,10)
random_arr

array([73, 22, 94, 25, 66, 11, 95, 90, 94, 69])

In [28]:
shape_arr = np.array([[1,2,3],[4,5,6]])
shape_arr
shape_arr.shape = (3,2)
shape_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
#vertical stack()
first_arr = np.array([1,2,3])
second_arr = np.array([4,5,6])
np.vstack((first_arr,second_arr))




array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
#horizontal stack()
np.hstack((first_arr,second_arr))

array([1, 2, 3, 4, 5, 6])

In [38]:
#column stack()
np.column_stack((second_arr,first_arr))

array([[4, 1],
       [5, 2],
       [6, 3]])