<a href="https://colab.research.google.com/github/SREENIVASAN-PRASANTH/Python-for-machine-Learning/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch as tp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(tp.__version__)

2.3.1+cu121


In [ ]:
!nvidia-smi

Thu Aug  1 14:53:03 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
###creating tensors
scalar = tp.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python integer
scalar.item()

7

In [5]:
#vector
vector = tp.tensor([7,7])
vector

tensor([7, 7])

vector.ndim

```
# This is formatted as code
```




In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
matrix = tp.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
matrix.ndim

2

In [13]:
matrix[1]

tensor([4, 5, 6])

In [14]:
matrix.shape

torch.Size([2, 3])

In [15]:
TENSOR = tp.tensor([[[1,2,3],[4,5,6],
                     [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])